### PR TITLE
Different Icons for non STI Demos and STI demos

### PR DESCRIPTION
**Pull request by Pacerino**
**Attention! New variable in the GeoJSON file!**

```json
"features":[
      {
        "type":"Feature",
        "properties":[
           {
              "fa_icon":"fa-map-marker",
              "value":"Bremen - Marktplatz"
           },
           {
              "fa_icon":"fa-clock-o",
              "value":"17.03.2019 13:30"
           },
           {
              "fa_icon":"fb_event",
              "value":"<a href=\"https://www.facebook.com/events/322508435067377/\">Facebook Event</a>"
           }
        ],
        "STIDemo": true,
        "geometry":{
           "type":"Point",
           "coordinates":[
              8.8049566,
              53.0757801
           ]
        }
     },
```

_`STIDemo`_ define if the Icon being used is for a STI demo or for a non STI demo!
_true_ for the STI icon, _false_ for a non STI demo

### CODE REVIEW

**Comment by Pacerino** [comment]
@NLDev please rebase and rebuild!

**Comment by NLDev** [comment]
That was a merge to dev only. No need to rebase :smile: 
And Dev is auto-build

**Comment by Pacerino** [comment]
Then merge it into Master and rebuild it on the server.  ¯\_(ツ)_/¯

Am 07.03.2019 12:03 schrieb "NullDev (Chris)" <notifications@github.com>:

That was a merge to dev only. No need to rebase 😄
And Dev is auto-build

**Comment by NLDev** [comment]
Fetzen? :^)

**Pull request merged**
