### PR TITLE
Add demo on 23rd March in Germany, Fürth to map

### PR DESCRIPTION
**Pull request by muellermartin**
Add marker for a demo on 23rd March in Fürth, Germany to map.

Announcement (besides Facebook event linked to marker): https://twitter.com/dieparteifuerth/status/1101547901195599872

Disclaimer: I'm not affiliated with the organisators of the demo.

### CODE REVIEW

**Comment by jonas32** [comment]
Thank you, but right now we only accept Demos that are approved by our coordination for legal reasons.
We already know about this Demo and will probably add it in the next days.

**Comment by muellermartin** [comment]
What can I do to help speeding up the progress to add it to the map? I think it is important to be quick as people might not attend if they are not able to plan timely in advance.

**Comment by jonas32** [comment]
You cant really do anything but as i see, Früth and Nürnberg got approved. They will be online in next 2 days.

**Comment by muellermartin** [comment]
Thanks for the quick reaction and merging! Are the approval criteria and the process for approval documented somewhere for better transparency?

**Comment by jonas32** [comment]
As far as i know they first want to make sure that the Demos are accepted by the City that they take place in. Thats bcs of legal reasons. There is a law that denies advertising not registered demos.

**Comment by muellermartin** [comment]
Hm, this sounds odd to me, because as far as I know demonstrations don't really need to be approved, they only need to be announced. Nothing more. And you don't have to wait for an "approval" until you can announce them publicly. But I'm no lawyer, so maybe I've got something wrong... If I find the time, I'll try to find out more. Thanks for merging nevertheless!

**Pull request merged**
