### PR TITLE
fix footer responsiveness

### LINKED ISSUE #48: [BUG] Footer Responsiveness
Somewhere along the line (probably in 88d8d9667cab2521e2c106c48fc0fab42da11213) the footers responsiveness was broken.

I think this is related to #44, since it's also an issue with the flexbox container no longer wrapping all its contents

ozpgs46 1
Responsive View

eozc8sv 1
Chrome DevTools, Samsung S5

image
Smartphone, OnePlus 3

### PR DESCRIPTION
**Pull request by schrej**
fixes #48

### CODE REVIEW

**Comment by kellerrennkadse** [comment]
Also, it seems like the div still doesn't wrap around its child elements, leaving the footer with the wrong background color

wiskgqm 1

Removing the `h-full`class from the `html` tag resolves the issue:
z5lv6me 1
akg0m5n 1

Removing the class also solves the issue of the `hero` element in the header not wrapping around its children. So.. maybe we should get rid of that one instead? Seeing that all the pages should have sufficient content by now?

**Comment by schrej** [comment]
Maybe removing `h-full` from `html` and replacing it with `.min-h-screen` on `body` is a better solution. I don't know when I have time to do it so feel free to test.

**Comment by schrej** [comment]
@kellerrennkadse should be good now

**Comment by NLDev** [comment]
Conflicts are resolved. @kellerrennkadse are the requested changes implemented?

**Comment by kellerrennkadse** [comment]
Should be implemented. Can't test atm though. If footer and header look okay, this should be fine

**Pull request merged**
