### PR TITLE
Environment support

### PR DESCRIPTION
**Pull request by kellerrennkadse**
Enables users to setup their own environment variables using a `.env` file

### CODE REVIEW

**Comment by schrej** [comment]
I'd prefer to have a config.example.ts that you have to copy before starting so you are able to modify it.

**Comment by kellerrennkadse** [comment]
That is exactly what you can do with the env file. The only difference is, that it's ignored by git, so you don't accidentally check in your secrets.

A env.dist file is provided, and I can add the automatic copy mechanism aswell. I just wanted to make sure people actually look at the file and fill in their details

**Comment by NLDev** [comment]
I'd honestly start to separate the stuff. 

- A config for server specific stuff such as port, cookie prefix and other things which are required for deployment as well as testing.
- An .env file dedicated to tokens, secrets, keys, etc which might not be that crucial for development

As for the config, we should completely move to a `config.template.ts` and add the original `config.ts` to the [.gitignore]}(https://github.com/savetheinternetinfo/website/blob/develop/.gitignore) file.

**Comment by kellerrennkadse** [comment]
I like the .env approach because it's incredibly simple.
No need for adding a comma at the end of the line, just values seperated by a new line. If you need to change the structure of your config file, you don't need to go back toyour deployed versions and fiddle with the config file, it just automatically works.

Also, having the `config.example.ts` file, merging changes is more complex ("where dows this block go?", "is this the right subkey?")

If I'm overruled on this one, that's fine for me. But I think an simple `.env` file is more convenient

**Comment by NLDev** [comment]
So this would lead back to my "separating stuff" approach [above](https://github.com/savetheinternetinfo/website/pull/46#issuecomment-400564279). I'd still prefer one universal config file instead of two different files which need to be configured.

**Comment by kellerrennkadse** [comment]
Only __one__ file needs to be configured. The other file just reads values from the other one, so everyone always has the same config file, without manually merging stuff and still can savely setup their secretsAm 28.06.2018 09:22 schrieb "NullDev (Chris)" <notifications@github.com>:So this would lead back to my "separating stuff" approach above. I'd still prefer one universal config file instead of two different files which need to be configured.

**Comment by kellerrennkadse** [comment]
Only __one__ file needs to be configured. You need to set your environment specific vars in the `.env` file.

The other file just reads values from the other one, so everyone always has the same config file, without manually merging stuff and still can savely setup their secrets.

And of course it comes back to seperating stuff.. This was the whole point of this PR

**Comment by NLDev** [comment]
Welp, my bad. Then I misunderstood.
`.env` sounds great!

**Pull request merged**
